qla2xxx-y := qla_os.o qla_init.o qla_mbx.o qla_iocb.o qla_isr.o qla_gs.o \
		qla_dbg.o qla_sup.o qla_attr.o qla_mid.o qla_dfs.o \
		ql2100_fw.o ql2200_fw.o ql2300_fw.o ql2322_fw.o \
		ql2400_fw.o ql2500_fw.o

obj-$(CONFIG_SCSI_QLA_FC) += qla2xxx.o
