# Make rules for configuration files.
#
# $Id: Makefile.config,v 1.2 2009/04/09 20:55:34 williams Exp $

CFG		= kernel-$(VERSION)

CONFIGFILES	= \
	$(CFG)-i686-rt.config \
	$(CFG)-i686-rtdebug.config \
	$(CFG)-i686-rttrace.config \
	$(CFG)-i686-rtvanilla.config \
	$(CFG)-x86_64-rt.config \
	$(CFG)-x86_64-rtdebug.config \
	$(CFG)-x86_64-rttrace.config \
	$(CFG)-x86_64-rtvanilla.config \

PLATFORMS	= x86 x86_64 
TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-generic temp-*-generic temp-*-generic-tmp
	@python sanity_check.py $(CONFIGFILES)

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config

# shared options
temp-generic: config-generic
	cat config-generic config-rt config-nodebug > temp-generic

temp-debug-generic: config-generic
	cat config-generic config-rt config-debug > temp-debug-generic

temp-trace-generic: config-generic
	cat config-generic config-rt config-trace > temp-trace-generic

temp-vanilla-generic: config-generic
	cat config-generic config-vanilla > temp-vanilla-generic

# x86 intermediate files
temp-x86-generic: config-x86-generic temp-generic
	perl merge.pl $^  > $@

temp-x86-debug-generic: config-x86-generic temp-debug-generic
	perl merge.pl $^  > $@

temp-x86-trace-generic: config-x86-generic temp-trace-generic
	perl merge.pl $^  > $@

temp-x86-vanilla-generic: config-x86-generic temp-vanilla-generic
	perl merge.pl $^  > $@

temp-x86_64-vanilla-generic: config-x86_64-generic temp-vanilla-generic
	perl merge.pl $^  > $@

# x86_64 intermediate files
temp-x86_64-generic: config-x86_64-generic temp-generic
	perl merge.pl $^  > $@

temp-x86_64-debug-generic: config-x86_64-generic temp-debug-generic
	perl merge.pl $^  > $@

temp-x86_64-trace-generic: config-x86_64-generic temp-trace-generic
	perl merge.pl $^  > $@


# i686 configs
kernel-$(VERSION)-i686-rt.config: config-i686-PAE temp-x86-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-rtdebug.config: config-i686-PAE temp-x86-debug-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-rttrace.config: config-i686-PAE temp-x86-trace-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-rtvanilla.config: config-i686-PAE temp-x86-vanilla-generic
	perl merge.pl $^ i386 > $@

# x86_64 configs
kernel-$(VERSION)-x86_64-rt.config: /dev/null temp-x86_64-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-x86_64-rtdebug.config: /dev/null temp-x86_64-debug-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-x86_64-rttrace.config: /dev/null temp-x86_64-trace-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-x86_64-rtvanilla.config: /dev/null temp-x86_64-vanilla-generic
	perl merge.pl $^ x86_64 > $@
